# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ADIA-Structural-Break-Challenge',
                'doc_host': 'https://Algoplexity.github.io',
                'git_url': 'https://github.com/Algoplexity/ADIA-Structural-Break-Challenge',
                'lib_path': 'ADIA_Structural_Break_Challenge'},
  'syms': { 'ADIA_Structural_Break_Challenge.core': { 'ADIA_Structural_Break_Challenge.core.foo': ( 'core.html#foo',
                                                                                                    'ADIA_Structural_Break_Challenge/core.py')}}}
